export const URIS = {
  login: "/login",
  getProblems: "/getProblems",
  getProblemsProgress: "/getProblemsProgress",
  getHeadLines: "getHeadLines",
  submitProblemCode: "/submitProblemCode",
  getProblemInfo: "/getProblemInfo",
  getAnswerScope: "/getAnswerScope",
  contestList: "/contestList",
  contestingState: "/contestingState",
  searchContestListByString: "/searchContestListByString",
  contestAnnouncement: "/contestAnnouncement",
  getStatusList: "/getStatusList",
  getStutusListByUser: "/getStutusListByUser",
  getStatusListByString: "/getStatusListByString",
  getRegionJson: "/getRegionJson",
  postUserMsg: "/postUserMsg",
  uploadHeadPic: "/uploadHeadPic",
  checkContestCode: "/checkContestCode",
  getContestingList: "/getContestingList",
  getUserMsg: "/getUserMsg",
  sendEmail: "/sendEmail",
};
